Repository jenkinsci/lib-file-leak-detector, pull requests merged in 2022-03, with the labels that each got.

#57 Migrate documentation to GitHub
  README.adoc
  pom.xml
  src/site/apt/index.apt
  src/site/site.xml
Labels: documentation

#58 Compile with Java 8
  pom.xml
Labels: skip-changelog

#59 Add a missing assertion to `TransformerTest`
  src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java
Labels: test

#60 Add a test for `AgentMain` which verifies that all classes from the spec are actually instrumented
  pom.xml
  src/test/java/org/kohsuke/file_leak_detector/AgentMainTest.java
Labels: test

#61 Amend help screen
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
Labels: documentation

#62 Clean up `TransformerTest`
  src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java
Labels: test

#63 Use Jenkins parent POM
  .gitignore
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: internal

#64 Add Dependabot configuration
  .github/dependabot.yml
Labels: dependencies

#67 Enable Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: internal

#71 Exclude unneeded args4j resources from shaded JAR
  pom.xml
Labels: dependencies

#72 Add support for Java 11
  Jenkinsfile
  pom.xml
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
  src/main/java/org/kohsuke/file_leak_detector/Main.java
  src/main/java/org/kohsuke/file_leak_detector/transform/CodeGenerator.java
  src/main/java/org/kohsuke/file_leak_detector/transform/MethodAppender.java
  src/main/java/org/kohsuke/file_leak_detector/transform/MethodTransformSpec.java
  src/main/java/org/kohsuke/file_leak_detector/transform/TransformerImpl.java
  src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java
Labels: enhancement

#73 Run tests on Windows
  Jenkinsfile
  src/test/java/org/kohsuke/file_leak_detector/instrumented/PipeDemo.java
Labels: test

#74 Miscellaneous code cleanup
  src/main/java/org/kohsuke/file_leak_detector/ActivityListener.java
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
  src/main/java/org/kohsuke/file_leak_detector/Listener.java
  src/main/java/org/kohsuke/file_leak_detector/Main.java
  src/main/java/org/kohsuke/file_leak_detector/transform/ClassTransformSpec.java
  src/main/java/org/kohsuke/file_leak_detector/transform/MethodAppender.java
  src/main/java/org/kohsuke/file_leak_detector/transform/TransformerImpl.java
  src/test/java/org/kohsuke/file_leak_detector/AgentMainTest.java
  src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/PipeDemo.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/SocketDemo.java
Labels: internal

#75 Improve README
  README.adoc
Labels: documentation

#77 Fix indentation in `pom.xml`
  pom.xml
Labels: skip-changelog

#76 Add support for `Files#newByteChannel` and `Files#newDirectoryStream`
  pom.xml
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
  src/main/java/org/kohsuke/file_leak_detector/Listener.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/FileDemo.java
Labels: enhancement

#78 Fine-grained SpotBugs exclusions
  pom.xml
  src/spotbugs/spotbugs-excludes.xml
Labels: skip-changelog

#79 Fix `DM_DEFAULT_ENCODING` SpotBugs violations
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
  src/main/java/org/kohsuke/file_leak_detector/Listener.java
  src/spotbugs/spotbugs-excludes.xml
  src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java
Labels: internal

#81 Adopt POM Code Convention
  pom.xml
Labels: skip-changelog

#85 Document options and link to file-leak-postprocess
  README.adoc
Labels: documentation

#84 Disable Socket to support (broken on Java 17+)
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
  src/main/java/org/kohsuke/file_leak_detector/Listener.java
  src/test/java/org/kohsuke/file_leak_detector/AgentMainTest.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/PipeDemo.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/SocketDemo.java
Labels: enhancement

#83 Add Java 17 to build/test matrix
  Jenkinsfile
Labels: test

#87 Clean up formatting
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
  src/main/java/org/kohsuke/file_leak_detector/Listener.java
  src/main/java/org/kohsuke/file_leak_detector/transform/TransformerImpl.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/SocketDemo.java
Labels: skip-changelog
