Repository jenkinsci/lib-file-leak-detector, pull requests merged in 2024-02, with the labels that each got.

#172 Format code with Spotless
  pom.xml
  src/main/java/org/kohsuke/file_leak_detector/ActivityListener.java
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
  src/main/java/org/kohsuke/file_leak_detector/Listener.java
  src/main/java/org/kohsuke/file_leak_detector/Main.java
  src/main/java/org/kohsuke/file_leak_detector/transform/CodeGenerator.java
  src/main/java/org/kohsuke/file_leak_detector/transform/MethodAppender.java
  src/main/java/org/kohsuke/file_leak_detector/transform/MethodTransformSpec.java
  src/main/java/org/kohsuke/file_leak_detector/transform/TransformerImpl.java
  src/test/java/org/kohsuke/file_leak_detector/AgentMainTest.java
  src/test/java/org/kohsuke/file_leak_detector/Bar.java
  src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/FileDemo.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/PipeDemo.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/SelectorDemo.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/SocketDemo.java
Labels: skip-changelog

#169 Avoid `UnsupportedOperationException` in `ZipPath#toFile` with JDK 17
  pom.xml
  src/main/java/org/kohsuke/file_leak_detector/ActivityListener.java
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
  src/main/java/org/kohsuke/file_leak_detector/Listener.java
  src/test/java/org/kohsuke/file_leak_detector/AgentMainTest.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/FileDemo.java
  src/test/resources/test.zip
Labels: bug

#161 Support files opened via `Files#newBufferedWriter`
  pom.xml
  src/main/java/org/kohsuke/file_leak_detector/AgentMain.java
  src/main/java/org/kohsuke/file_leak_detector/Listener.java
  src/test/java/org/kohsuke/file_leak_detector/instrumented/FileDemo.java
Labels: enhancement
